# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfood', '0003_userpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpage',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos'),
        ),
    ]
