# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfood', '0004_userpage_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpage',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
