# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfood', '0005_userpage_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpage',
            name='description',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
    ]
