# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfood', '0006_auto_20160717_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpage',
            name='userhandle',
            field=models.CharField(default='username', max_length=20),
            preserve_default=False,
        ),
    ]
