# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-26 02:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfood', '0010_remove_savedrecipe_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedrecipe',
            name='recipe_key',
            field=models.CharField(default='key', max_length=200),
            preserve_default=False,
        ),
    ]
