# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-26 12:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appfood', '0011_savedrecipe_recipe_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedrecipe',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
