# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-26 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfood', '0012_savedrecipe_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedrecipe',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
