# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 14:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('appfood', '0016_auto_20160727_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 7, 27, 14, 4, 49, 550575, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
