# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfood', '0018_fooditem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
