# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 12:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('appfood', '0021_auto_20160727_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedrecipe',
            name='bookmark_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 7, 28, 12, 23, 48, 192561, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
