# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfood', '0022_savedrecipe_bookmark_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='measurementunit',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
