# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfood', '0023_fooditem_measurementunit'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='detailed_ingredients',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
