# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-29 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfood', '0024_recipe_detailed_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedrecipe',
            name='detailed_ingredients',
            field=models.TextField(default='oops'),
            preserve_default=False,
        ),
    ]
