# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-31 02:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('appfood', '0028_useruploadedrecipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='useruploadedrecipe',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 7, 31, 2, 31, 34, 237833, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
