# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-31 05:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appfood', '0030_uploadedrecipebookmark'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadedrecipebookmark',
            old_name='uploader',
            new_name='user',
        ),
    ]
