# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-01 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfood', '0031_auto_20160731_0505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpage',
            name='userhandle',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
