# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-01 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfood', '0034_auto_20160801_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedrecipebookmark',
            name='bookmark_notes',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
