# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-02 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfood', '0035_auto_20160801_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpage',
            name='bookmarks_private',
            field=models.BooleanField(default=False),
        ),
    ]
