# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-02 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfood', '0037_useruploadedrecipe_recipe_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpage',
            name='uploads_private',
            field=models.BooleanField(default=False),
        ),
    ]
