# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-03 12:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appfood', '0038_userpage_uploads_private'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fooditem',
            old_name='date_added',
            new_name='last_edit',
        ),
    ]
